(deftheme challenger-deep
  "Created 2018-07-28.")

(custom-theme-set-faces
 'challenger-deep
 '(bold ((((class color) (min-colors 257)) (:weight bold :color "#cbe3e7")) (((class color) (min-colors 89)) (:weight bold :color "#cbe3e7"))))
 '(italic ((((class color) (min-colors 257)) (:slant italic))))
 '(bold-italic ((((class color) (min-colors 257)) (:weight bold :slant italic :foreground "#cbe3e7")) (((class color) (min-colors 89)) (:weight bold :slant italic :foreground "#cbe3e7"))))
 '(line-number ((((class color) (min-colors 257)) (:background "#100e23" :foreground "#565575")) (((class color) (min-colors 89)) (:background "#121212" :foreground "#808080"))))
 '(line-number-current-line ((((class color) (min-colors 257)) (:background "#100e23" :foreground "#91ddff")) (((class color) (min-colors 89)) (:background "#121212" :foreground "#87d7ff"))))
 '(fringe ((((class color) (min-colors 257)) (:inherit default :foreground "#565575")) (((class color) (min-colors 89)) (:inherit default :foreground "#808080"))))
 '(region ((((class color) (min-colors 257)) (:background "#3d4451")) (((class color) (min-colors 89)) (:background "#3d4451"))))
 '(highlight ((((class color) (min-colors 257)) (:background "#906cff" :foreground "#100e23")) (((class color) (min-colors 89)) (:background "#875fd7" :foreground "#121212"))))
 '(cursor ((((class color) (min-colors 257)) (:background "#91ddff")) (((class color) (min-colors 89)) (:background "#87d7ff"))))
 '(shadow ((((class color) (min-colors 257)) (:foreground "#cbe3e7")) (((class color) (min-colors 89)) (:foreground "#eeeeee"))))
 '(minibuffer-prompt ((((class color) (min-colors 257)) (:foreground "#91ddff")) (((class color) (min-colors 89)) (:foreground "#87d7ff"))))
 '(tooltip ((((class color) (min-colors 257)) (:background "#100e23" :foreground "#cbe3e7")) (((class color) (min-colors 89)) (:background "#121212" :foreground "#eeeeee"))))
 '(error ((((class color) (min-colors 257)) (:foreground "#ff8080")) (((class color) (min-colors 89)) (:foreground "#ff8787"))))
 '(warning ((((class color) (min-colors 257)) (:foreground "#ffe9aa")) (((class color) (min-colors 89)) (:foreground "#ffd75f"))))
 '(success ((((class color) (min-colors 257)) (:foreground "#95ffa4")) (((class color) (min-colors 89)) (:foreground "#5fffaf"))))
 '(secondary-selection ((((class color) (min-colors 257)) (:background "#91ddff" :foreground "#100e23")) (((class color) (min-colors 89)) (:background "#87d7ff" :foreground "#121212"))))
 '(lazy-highlight ((((class color) (min-colors 257)) (:background "#65b2ff" :foreground "#cbe3e7")) (((class color) (min-colors 89)) (:background "#5fafff" :foreground "#eeeeee"))))
 '(match ((((class color) (min-colors 257)) (:foreground "#95ffa4" :background "#100e23" :bold t)) (((class color) (min-colors 89)) (:foreground "#5fffaf" :background "#121212" :bold t))))
 '(trailing-whitespace ((((class color) (min-colors 257)) (:background "#ff5458")) (((class color) (min-colors 89)) (:background "#ff5f00"))))
 '(vertical-border ((((class color) (min-colors 257)) (:foreground "#100e23" :background "#100e23")) (((class color) (min-colors 89)) (:foreground "#121212" :background "#121212"))))
 '(show-paren-match ((((class color) (min-colors 257)) (:background "#65b2ff" :foreground "#100e23")) (((class color) (min-colors 89)) (:background "#5fafff" :foreground "#121212"))))
 '(linum ((((class color) (min-colors 257)) (:background "#100e23" :foreground "#565575" :bold)) (((class color) (min-colors 89)) (:background "#121212" :foreground "#808080" :bold))))
 '(font-lock-builtin-face ((((class color) (min-colors 257)) (:foreground "#c991e1")) (((class color) (min-colors 89)) (:foreground "#d7afff"))))
 '(font-lock-comment-face ((((class color) (min-colors 257)) (:foreground "#565575")) (((class color) (min-colors 89)) (:foreground "#808080"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 257)) (:foreground "#565575")) (((class color) (min-colors 89)) (:foreground "#808080"))))
 '(font-lock-doc-face ((((class color) (min-colors 257)) (:foreground "#62d196")) (((class color) (min-colors 89)) (:foreground "#5fd787"))))
 '(font-lock-constant-face ((((class color) (min-colors 257)) (:foreground "#aaffe4")) (((class color) (min-colors 89)) (:foreground "#87ffff"))))
 '(font-lock-function-name-face ((((class color) (min-colors 257)) (:foreground "#c991e1")) (((class color) (min-colors 89)) (:foreground "#d7afff"))))
 '(font-lock-keyword-face ((((class color) (min-colors 257)) (:foreground "#ff8080")) (((class color) (min-colors 89)) (:foreground "#ff8787"))))
 '(font-lock-string-face ((((class color) (min-colors 257)) (:foreground "#ffe9aa")) (((class color) (min-colors 89)) (:foreground "#ffd75f"))))
 '(font-lock-type-face ((((class color) (min-colors 257)) (:foreground "#91ddff")) (((class color) (min-colors 89)) (:foreground "#87d7ff"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 257)) (:foreground "#ffe9aa")) (((class color) (min-colors 89)) (:foreground "#ffd75f"))))
 '(font-lock-warning-face ((((class color) (min-colors 257)) (:inherit warning)) (((class color) (min-colors 89)) (:inherit warning))))
 '(font-lock-negation-char-face ((((class color) (min-colors 257)) (:foreground "#63f2f1" :bold t)) (((class color) (min-colors 89)) (:foreground "#00ffff" :bold t))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 257)) (:foreground "#63f2f1" :bold t)) (((class color) (min-colors 89)) (:foreground "#00ffff" :bold t))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 257)) (:foreground "#63f2f1" :bold t)) (((class color) (min-colors 89)) (:foreground "#00ffff" :bold t))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 257)) (:foreground "#63f2f1" :bold t)) (((class color) (min-colors 89)) (:foreground "#00ffff" :bold t))))
 '(mode-line ((((class color) (min-colors 257)) (:foreground "#cbe3e7" :background "#100e23")) (((class color) (min-colors 89)) (:foreground "#eeeeee" :background "#121212"))))
 '(mode-line-inactive ((((class color) (min-colors 257)) (:foreground "#565575" :background "#100e23")) (((class color) (min-colors 89)) (:foreground "#808080" :background "#121212"))))
 '(header-line ((((class color) (min-colors 257)) (:inherit mode-line)) (((class color) (min-colors 89)) (:inherit mode-line))))
 '(isearch ((((class color) (min-colors 257)) (:background "#aaffe4" :foreground "#100e23" :bold t)) (((class color) (min-colors 89)) (:background "#87ffff" :foreground "#121212" :bold t))))
 '(window-divider ((((class color) (min-colors 257)) (:foreground "#100e23")) (((class color) (min-colors 89)) (:foreground "#121212"))))
 '(window-divider-first-pixel ((((class color) (min-colors 257)) (:foreground "#100e23")) (((class color) (min-colors 89)) (:foreground "#121212"))))
 '(window-divider-last-pixel ((((class color) (min-colors 257)) (:foreground "#100e23")) (((class color) (min-colors 89)) (:foreground "#121212"))))
 '(evil-ex-substitute-matches ((((class color) (min-colors 257)) (:background "#100e23" :foreground "#ff8080" :strike-through t :bold t)) (((class color) (min-colors 89)) (:background "#121212" :foreground "#ff8787" :strike-through t :bold t))))
 '(evil-ex-substitute-replacement ((((class color) (min-colors 257)) (:background "#100e23" :foreground "#95ffa4" :bold t)) (((class color) (min-colors 89)) (:background "#121212" :foreground "#5fffaf" :bold t))))
 '(flyspell-incorrect ((((class color) (min-colors 257)) (:underline (:style wave :color "#ff8080") :inherit unspecified)) (((class color) (min-colors 89)) (:underline (:style wave :color "#ff8787") :inherit unspecified))))
 '(default ((t (:background "#1b182c" :foreground "gray78")))))

(provide-theme 'challenger-deep)
